from linebot.models import FlexSendMessage, BubbleContainer, CarouselContainer, ImageComponent, BoxComponent, \
    TextComponent, IconComponent


def TestFlex():
    host = "https://"
    urls = {0: f"{host}shiawaseninaritai.com/wp-content/uploads/2019/05/39f94af6e839a79ce57553873b282f7b-728x427.png",
            1: f"{host}livedoor.blogimg.jp/jin115/imgs/6/1/61d89d0f.jpg",
            2: f"{host}i.ytimg.com/vi/Mr5gPPYBlg8/maxresdefault.jpg"}

    stars = {0: f"{host}scdn.line-apps.com/n/channel_devcenter/img/fx/review_gold_star_28.png",
             1: f"{host}scdn.line-apps.com/n/channel_devcenter/img/fx/review_gray_star_28.png"}

    flex = CarouselContainer(
        contents=[
            BubbleContainer(
                size="micro",
                hero=ImageComponent(
                    type="image",
                    url=urls[0],
                    size="full",
                    aspectMode="cover",
                    aspectRatio="320:213"
                ),
                body=BoxComponent(
                    layout="vertical",
                    contents=[
                        TextComponent(
                            text="ゆゆうた",
                            weight="bold",
                            size="sm",
                            wrap=True
                        ),
                        BoxComponent(
                            ayout="baseline",
                            contents=[
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                TextComponent(
                                    text="4.0",
                                    size="xs",
                                    color="#8c8c8c",
                                    margin="md",
                                    flex=0
                                )
                            ]
                        ),
                        BoxComponent(
                            layout="vertical",
                            contents=[
                                BoxComponent(
                                    layout="baseline",
                                    spacing="sm",
                                    contents=[
                                        TextComponent(
                                            text="OMMC",
                                            wrap=True,
                                            color="#8c8c8c",
                                            size="xs",
                                            flex=5
                                        )
                                    ]
                                )
                            ]
                        )
                    ],
                    spacing="sm",
                    paddingAll="13px"
                )
            ),
            BubbleContainer(
                size="micro",
                hero=ImageComponent(
                    url=urls[1],
                    size="full",
                    aspectMode="cover",
                    aspectRatio="320:213"
                ),
                body=BoxComponent(
                    layout="vertical",
                    contents=[
                        TextComponent(
                            text="からさわたかひろ",
                            weight="bold",
                            size="sm",
                            wrap=True
                        ),
                        BoxComponent(
                            layout="baseline",
                            contents=[
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                IconComponent(
                                    size="xs",
                                    url=stars[0]
                                ),
                                TextComponent(
                                    text="4.0",
                                    size="sm",
                                    color="#8c8c8c",
                                    margin="md",
                                    flex=0
                                )
                            ]
                        ),
                        BoxComponent(
                            layout="vertical",
                            contents=[
                                BoxComponent(
                                    layout="baseline",
                                    spacing="sm",
                                    contents=[
                                        TextComponent(
                                            text="あああああああ",
                                            wrap=True,
                                            color="#8c8c8c",
                                            size="xs",
                                            flex=5
                                        )
                                    ]
                                )
                            ]
                        )
                    ],
                    spacing="sm",
                    paddingAll="13px"
                )
            ),
            BubbleContainer(
                size="micro",
                hero=ImageComponent(
                    url=urls[2],
                    size="full",
                    aspectMode="cover",
                    aspectRatio="320:213"
                ),
                body=BoxComponent(
                    layout="vertical",
                    contents=[
                        TextComponent(
                            text="しゃむ",
                            weight="bold",
                            size="sm"
                        ),
                        BoxComponent(
                            BoxComponent(
                                layout="baseline",
                                contents=[
                                    IconComponent(
                                        size="xs",
                                        url=stars[1]
                                    ),
                                    IconComponent(
                                        size="xs",
                                        url=stars[1]
                                    ),
                                    IconComponent(
                                        size="xs",
                                        url=stars[1]
                                    ),
                                    IconComponent(
                                        size="xs",
                                        url=stars[1]
                                    ),
                                    IconComponent(
                                        size="xs",
                                        url=stars[1]
                                    ),
                                    TextComponent(
                                        text="4.0",
                                        size="sm",
                                        color="#8c8c8c",
                                        margin="md",
                                        flex=0
                                    )
                                ]
                            ),
                            BoxComponent(
                                layout="vertical",
                                contents=[
                                    BoxComponent(
                                        layout="baseline",
                                        spacing="sm",
                                        contents=[
                                            TextComponent(
                                                text="それってYO！",
                                                wrap=True,
                                                color="#8c8c8c",
                                                size="xs",
                                                flex=5
                                            )
                                        ]
                                    )
                                ]
                            )
                        )
                    ],
                    spacing="sm",
                    paddingAll="13px"
                )
            )
        ]
    )
    return flex
